### ISSUE TITLE
imagesize module alternative

### ISSUE THREAD

**Issue by mdmoreau** [Sunify/gulp-baseimg#2]
Any chance you'd be willing to use https://github.com/image-size/image-size instead of the existing imagesize module?  Switching to that one would support width/height from SVGs by using the viewbox values if width/height aren't specified.

**Comment by Sunify** [comment]
Thanks for this issue! Now i use image-size.

**Comment by mdmoreau** [comment]
Awesome - thanks!  Works perfectly now without having to supply width/height for SVGs.
